server:
  port: 8888
spring:
  application:
    name: app-code-generator-sample
  cloud:
    nacos:
      server-addr: 10.10.20.90:8848
    inetutils:
      preferred-networks: 10.10
  autoconfigure:
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  datasource:
    druid:
      stat-view-servlet:
        enabled: true
        loginUsername: admin
        loginPassword: 123456
        allow:
      web-stat-filter:
        enabled: true
    dynamic:
      druid: # 全局druid参数，绝大部分值和默认保持一致。(现已支持的参数如下,不清楚含义不要乱设置)
        # 连接池的配置信息
        # 初始化大小，最小，最大
        initial-size: 5
        min-idle: 5
        maxActive: 20
        # 配置获取连接等待超时的时间
        maxWait: 60000
        # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        timeBetweenEvictionRunsMillis: 60000
        # 配置一个连接在池中最小生存的时间，单位是毫秒
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        # 打开PSCache，并且指定每个连接上PSCache的大小
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
        filters: stat,wall,slf4j
        # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
        connectionProperties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
      datasource:
        master:
          url: jdbc:mysql://81.70.161.37:3306/code-generator-sample?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
          username: root
          password: 1qaz@WSXcc123
          driver-class-name: com.mysql.cj.jdbc.Driver
          # 多数据源配置
          #multi-datasource1:
          #url: jdbc:mysql://localhost:3306/jeecg-boot2?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
          #username: root
          #password: root
          #driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    allow-bean-definition-overriding: true
#  redis:
#    host: 10.10.20.90
#    lettuce:
#      pool:
#        max-active: 8
#        max-idle: 8
#        max-wait: -1
#        min-idle: 0
#    port: 6379
#    timeout: 5000
#    password: ldsk1234

feign:
  client:
    config:
      feignName:
        connectTimeout: 30000
        readTimeout: 30000
  compression:
    request:
      enabled: false
      mime-types: text/xml,application/xml,application/json
      min-request-size: 2048
    response:
      enabled: false
  httpclient:
    enabled: false
    max-connections: 1000
    max-connections-per-route: 100
  hystrix:
    enabled: false
  okhttp:
    enabled: true
#  sentinel:
#    enabled: true
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
mybatis-plus:
  configuration:
    cache-enabled: false
    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      field-strategy: NOT_NULL
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto
      logic-delete-field: delFlag
  mapper-locations: classpath*:com/ludan/**/xml/*Mapper.xml
#  mapper-locations: classpath*:com/ludan/demo/**/xml/*Mapper.xml #classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.ludan.demo.entity,com.ludan.demo.dto
  type-enums-package: com.ludan.demo.entity,com.ludan.demo.dto

logging:
  level:
    com.ludan: debug
#ludan:
#  #  审计日志
#  audit-log:
#    enabled: true
#    log-type: db
#    datasource:
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      jdbc-url: jdbc:mysql://10.10.20.90:3306/frame_audit?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
#      username: d_frame_opr
#      password: gVX+9geD_uQTb5th

ribbon:
  ConnectTimeout: 30000
  MaxAutoRetriesNextServer: 0
  ReadTimeout: 30000
  ServerListRefreshInterval: 15000

env: dev # dev/sit/prod
